package com.thinkgem.jeesite.modules.tz.dao;

import com.thinkgem.jeesite.common.persistence.annotation.MyBatisDao;
import com.thinkgem.jeesite.modules.tz.entity.TzSfOrgIndex;
import com.thinkgem.jeesite.modules.tz.entity.TzSfOrgIndexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisDao
public interface TzSfOrgIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org_index
     *
     * @mbggenerated
     */
    int countByExample(TzSfOrgIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org_index
     *
     * @mbggenerated
     */
    int deleteByExample(TzSfOrgIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org_index
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org_index
     *
     * @mbggenerated
     */
    int insert(TzSfOrgIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org_index
     *
     * @mbggenerated
     */
    int insertSelective(TzSfOrgIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org_index
     *
     * @mbggenerated
     */
    List<TzSfOrgIndex> selectByExample(TzSfOrgIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org_index
     *
     * @mbggenerated
     */
    TzSfOrgIndex selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org_index
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TzSfOrgIndex record, @Param("example") TzSfOrgIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org_index
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TzSfOrgIndex record, @Param("example") TzSfOrgIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TzSfOrgIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TzSfOrgIndex record);


	TzSfOrgIndex selectByInfoExample(TzSfOrgIndexExample orgIndexExample);
}