package com.thinkgem.jeesite.modules.tz.dao;

import com.thinkgem.jeesite.common.persistence.annotation.MyBatisDao;
import com.thinkgem.jeesite.modules.tz.entity.TzSfDividend;
import com.thinkgem.jeesite.modules.tz.entity.TzSfDividendExample;
import com.thinkgem.jeesite.modules.tz.entity.TzSfInfo;
import com.thinkgem.jeesite.modules.tz.entity.TzSfInfoExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisDao
public interface TzSfDividendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_dividend
     *
     * @mbggenerated
     */
    int countByExample(TzSfDividendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_dividend
     *
     * @mbggenerated
     */
    int deleteByExample(TzSfDividendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_dividend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_dividend
     *
     * @mbggenerated
     */
    int insert(TzSfDividend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_dividend
     *
     * @mbggenerated
     */
    int insertSelective(TzSfDividend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_dividend
     *
     * @mbggenerated
     */
    List<TzSfDividend> selectByExample(TzSfDividendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_dividend
     *
     * @mbggenerated
     */
    TzSfDividend selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_dividend
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TzSfDividend record, @Param("example") TzSfDividendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_dividend
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TzSfDividend record, @Param("example") TzSfDividendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_dividend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TzSfDividend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_dividend
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TzSfDividend record);
    
    TzSfDividend selectByInfoExample(TzSfDividendExample record);
}