package com.thinkgem.jeesite.modules.tz.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.thinkgem.jeesite.common.persistence.annotation.MyBatisDao;
import com.thinkgem.jeesite.modules.tz.entity.TzSfMember;
import com.thinkgem.jeesite.modules.tz.entity.TzSfMemberExample;

@MyBatisDao
public interface TzSfMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member
     *
     * @mbggenerated
     */
    int countByExample(TzSfMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member
     *
     * @mbggenerated
     */
    int deleteByExample(TzSfMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member
     *
     * @mbggenerated
     */
    int insert(TzSfMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member
     *
     * @mbggenerated
     */
    int insertSelective(TzSfMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member
     *
     * @mbggenerated
     */
    List<TzSfMember> selectByExample(TzSfMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member
     *
     * @mbggenerated
     */
    TzSfMember selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TzSfMember record, @Param("example") TzSfMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TzSfMember record, @Param("example") TzSfMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TzSfMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TzSfMember record);
    
    TzSfMember selectByInfoExample(TzSfMemberExample example);
}