package com.thinkgem.jeesite.modules.tz.dao;

import com.thinkgem.jeesite.common.persistence.annotation.MyBatisDao;
import com.thinkgem.jeesite.modules.tz.entity.TzSfTypeIndex;
import com.thinkgem.jeesite.modules.tz.entity.TzSfTypeIndexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisDao
public interface TzSfTypeIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type_index
     *
     * @mbggenerated
     */
    int countByExample(TzSfTypeIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type_index
     *
     * @mbggenerated
     */
    int deleteByExample(TzSfTypeIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type_index
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type_index
     *
     * @mbggenerated
     */
    int insert(TzSfTypeIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type_index
     *
     * @mbggenerated
     */
    int insertSelective(TzSfTypeIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type_index
     *
     * @mbggenerated
     */
    List<TzSfTypeIndex> selectByExample(TzSfTypeIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type_index
     *
     * @mbggenerated
     */
    TzSfTypeIndex selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type_index
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TzSfTypeIndex record, @Param("example") TzSfTypeIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type_index
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TzSfTypeIndex record, @Param("example") TzSfTypeIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TzSfTypeIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TzSfTypeIndex record);
}