package com.thinkgem.jeesite.modules.tz.dao;

import com.thinkgem.jeesite.common.persistence.annotation.MyBatisDao;
import com.thinkgem.jeesite.modules.tz.entity.TzSfInfo;
import com.thinkgem.jeesite.modules.tz.entity.TzSfInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisDao
public interface TzSfInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_info
     *
     * @mbggenerated
     */
    int countByExample(TzSfInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_info
     *
     * @mbggenerated
     */
    int deleteByExample(TzSfInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_info
     *
     * @mbggenerated
     */
    int insert(TzSfInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_info
     *
     * @mbggenerated
     */
    int insertSelective(TzSfInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_info
     *
     * @mbggenerated
     */
    List<TzSfInfo> selectByExample(TzSfInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_info
     *
     * @mbggenerated
     */
    TzSfInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TzSfInfo record, @Param("example") TzSfInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TzSfInfo record, @Param("example") TzSfInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TzSfInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TzSfInfo record);
    
    
    TzSfInfo selectByInfoExample(TzSfInfoExample record);
}