package com.thinkgem.jeesite.modules.tz.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.thinkgem.jeesite.common.persistence.annotation.MyBatisDao;
import com.thinkgem.jeesite.modules.fund.entity.spider.TsFundNv;
import com.thinkgem.jeesite.modules.tz.entity.TzSfNv;
import com.thinkgem.jeesite.modules.tz.entity.TzSfNvExample;

@MyBatisDao
public interface TzSfNvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_nv
     *
     * @mbggenerated
     */
    int countByExample(TzSfNvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_nv
     *
     * @mbggenerated
     */
    int deleteByExample(TzSfNvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_nv
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_nv
     *
     * @mbggenerated
     */
    int insert(TzSfNv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_nv
     *
     * @mbggenerated
     */
    int insertSelective(TzSfNv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_nv
     *
     * @mbggenerated
     */
    List<TzSfNv> selectByExample(TzSfNvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_nv
     *
     * @mbggenerated
     */
    TzSfNv selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_nv
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TzSfNv record, @Param("example") TzSfNvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_nv
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TzSfNv record, @Param("example") TzSfNvExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_nv
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TzSfNv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_nv
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TzSfNv record);

	String selectLastNvDate(TzSfNv nv);

	TzSfNv selectByInfoExample(TzSfNvExample nvExample);
}