package com.thinkgem.jeesite.modules.tz.dao;

import com.thinkgem.jeesite.common.persistence.annotation.MyBatisDao;
import com.thinkgem.jeesite.modules.tz.entity.TzSfOrg;
import com.thinkgem.jeesite.modules.tz.entity.TzSfOrgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisDao
public interface TzSfOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org
     *
     * @mbggenerated
     */
    int countByExample(TzSfOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org
     *
     * @mbggenerated
     */
    int deleteByExample(TzSfOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org
     *
     * @mbggenerated
     */
    int insert(TzSfOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org
     *
     * @mbggenerated
     */
    int insertSelective(TzSfOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org
     *
     * @mbggenerated
     */
    List<TzSfOrg> selectByExample(TzSfOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org
     *
     * @mbggenerated
     */
    TzSfOrg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TzSfOrg record, @Param("example") TzSfOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TzSfOrg record, @Param("example") TzSfOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TzSfOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_org
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TzSfOrg record);
    
    
    TzSfOrg selectByInfoExample(TzSfOrgExample example);
}