package com.thinkgem.jeesite.modules.tz.dao;

import com.thinkgem.jeesite.common.persistence.annotation.MyBatisDao;
import com.thinkgem.jeesite.modules.tz.entity.TzSfType;
import com.thinkgem.jeesite.modules.tz.entity.TzSfTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisDao
public interface TzSfTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type
     *
     * @mbggenerated
     */
    int countByExample(TzSfTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type
     *
     * @mbggenerated
     */
    int deleteByExample(TzSfTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type
     *
     * @mbggenerated
     */
    int insert(TzSfType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type
     *
     * @mbggenerated
     */
    int insertSelective(TzSfType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type
     *
     * @mbggenerated
     */
    List<TzSfType> selectByExample(TzSfTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type
     *
     * @mbggenerated
     */
    TzSfType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TzSfType record, @Param("example") TzSfTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TzSfType record, @Param("example") TzSfTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TzSfType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TzSfType record);
}