package com.thinkgem.jeesite.modules.tz.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.thinkgem.jeesite.common.persistence.annotation.MyBatisDao;
import com.thinkgem.jeesite.modules.tz.entity.TzSfStock;
import com.thinkgem.jeesite.modules.tz.entity.TzSfStockExample;

@MyBatisDao
public interface TzSfStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_stock
     *
     * @mbggenerated
     */
    int countByExample(TzSfStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_stock
     *
     * @mbggenerated
     */
    int deleteByExample(TzSfStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_stock
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_stock
     *
     * @mbggenerated
     */
    int insert(TzSfStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_stock
     *
     * @mbggenerated
     */
    int insertSelective(TzSfStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_stock
     *
     * @mbggenerated
     */
    List<TzSfStock> selectByExample(TzSfStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_stock
     *
     * @mbggenerated
     */
    TzSfStock selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_stock
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TzSfStock record, @Param("example") TzSfStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_stock
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TzSfStock record, @Param("example") TzSfStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_stock
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TzSfStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_stock
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TzSfStock record);
    
    TzSfStock selectByInfoExample(TzSfStockExample example);
}