package com.thinkgem.jeesite.modules.tz.dao;

import com.thinkgem.jeesite.common.persistence.annotation.MyBatisDao;
import com.thinkgem.jeesite.modules.tz.entity.TzSfMemberIndex;
import com.thinkgem.jeesite.modules.tz.entity.TzSfMemberIndexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisDao
public interface TzSfMemberIndexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member_index
     *
     * @mbggenerated
     */
    int countByExample(TzSfMemberIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member_index
     *
     * @mbggenerated
     */
    int deleteByExample(TzSfMemberIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member_index
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member_index
     *
     * @mbggenerated
     */
    int insert(TzSfMemberIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member_index
     *
     * @mbggenerated
     */
    int insertSelective(TzSfMemberIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member_index
     *
     * @mbggenerated
     */
    List<TzSfMemberIndex> selectByExample(TzSfMemberIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member_index
     *
     * @mbggenerated
     */
    TzSfMemberIndex selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member_index
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TzSfMemberIndex record, @Param("example") TzSfMemberIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member_index
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TzSfMemberIndex record, @Param("example") TzSfMemberIndexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TzSfMemberIndex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_member_index
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TzSfMemberIndex record);

	TzSfMemberIndex selectByInfoExample(
			TzSfMemberIndexExample memberIndexExample);
}