package com.thinkgem.jeesite.modules.tz.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.thinkgem.jeesite.common.persistence.annotation.MyBatisDao;
import com.thinkgem.jeesite.modules.tz.entity.TzSfSplit;
import com.thinkgem.jeesite.modules.tz.entity.TzSfSplitExample;

@MyBatisDao
public interface TzSfSplitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_split
     *
     * @mbggenerated
     */
    int countByExample(TzSfSplitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_split
     *
     * @mbggenerated
     */
    int deleteByExample(TzSfSplitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_split
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_split
     *
     * @mbggenerated
     */
    int insert(TzSfSplit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_split
     *
     * @mbggenerated
     */
    int insertSelective(TzSfSplit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_split
     *
     * @mbggenerated
     */
    List<TzSfSplit> selectByExample(TzSfSplitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_split
     *
     * @mbggenerated
     */
    TzSfSplit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_split
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TzSfSplit record, @Param("example") TzSfSplitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_split
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TzSfSplit record, @Param("example") TzSfSplitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_split
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TzSfSplit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz_sf_split
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TzSfSplit record);
    
    TzSfSplit selectByInfoExample(TzSfSplitExample example);
}